[[constraint]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.10.5"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "1.10.5"

[[override]]
  name = "github.com/json-iterator/go"
  branch = "master"

[[override]]
  name = "github.com/docker/distribution"
  branch = "master"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.10.5"


